//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public int Player1Id { get; set; }
        public int Player2Id { get; set; }
        public string GridJson { get; set; }
        public int CurrentTurnId { get; set; }
        public string Status { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public DateTime CreatedAt { get; set; }


        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual Players Players2 { get; set; }
        public virtual Players Players3 { get; set; }
    }
}
